version: '3.8'

services:
  node-exporter:
    image: prom/node-exporter
    ports:
      - 9100:9100

  prometheus:
    image: quay.io/prometheus/prometheus
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    volumes:
      - ./prometheus/:/etc/prometheus/

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
