version: "3"
services:
  app:
    image: app
    build: ./app
    ports:
      - 8080:8080
      - 8081:8081
    networks:
      - monitoring

  prometheus:
    image: quay.io/prometheus/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    command: "--config.file=/etc/prometheus/prometheus.yaml --storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090
    networks:
      - monitoring
  
  alertmanager:
    image: quay.io/prometheus/alertmanager
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    ports:
      - 9093:9093
    networks:
      - monitoring
    
  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana/provisioning/datasources/:/etc/grafana/provisioning/datasources/
    environment:
      - GF_PATH_PROVISIONING=/etc/grafana/provisioning
    ports:
      - 3000:3000 
    networks:
      - monitoring

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - monitoring
  
  stunnel:
    image: dweomer/stunnel
    environment:
      - STUNNEL_SERVICE=smtps
      - STUNNEL_ACCEPT=465
      - STUNNEL_CONNECT=mailhog:1025
    ports:
      - 465:465
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge