global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - 'node-exporter.yaml'

scrape_configs:
- job_name: 'node-exporter'
  static_configs:
  - targets: ['node-exporter:9100']

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
