global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - "./rules.yaml"

scrape_configs:
  - job_name: 'java-app'
    scrape_interval: 5s
    static_configs:
      - targets: ['java-app:8081']
    metrics_path: "/actuator/prometheus"
  - job_name: 'python-app'
    scrape_interval: 5s
    static_configs:
      - targets: ['python-app:8000']

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
