global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - "./rules.yaml"

scrape_configs:
  - job_name: 'app'
    scrape_interval: 5s
    static_configs:
      - targets: ['app:8081']
    metrics_path: "/actuator/prometheus"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
