version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./insert_template.js:/docker-entrypoint-initdb.d/insert_template.js  

  mongo-exporter:
    image: bitnami/mongodb-exporter:latest
    container_name: mongo_exporter
    environment:
      MONGODB_URI: "mongodb://mongo:27017"
    ports:
      - "9216:9216"

volumes:
  mongo_data: