global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
- "./rules.yaml"

scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets: ['prometheus:9090']
- job_name: 'caadvisor'
  static_configs:
  - targets: ['cadvisor:8080']
- job_name: 'grafana'
  static_configs:
  - targets: ['grafana:3000']
- job_name: 'node-exporter'
  static_configs:
  - targets: ['node-exporter:9100']

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
