services:
  prometheus:
    image: quay.io/prometheus/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    command: "--config.file=/etc/prometheus/prometheus.yaml --storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning/
    environment:
      GF_PATH_PROVISIONING: /etc/grafana/provisioning
      GF_LOG_LEVEL: info
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: grafana
    ports:
      - 3000:3000 
  
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    privileged: true
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro

  node-exporter:
    image: prom/node-exporter
    ports:
      - 9100:9100 
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'   
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'

  alertmanager:
    image: quay.io/prometheus/alertmanager
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    ports:
      - 9093:9093

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025

  stunnel:
    image: dweomer/stunnel
    environment:
      - STUNNEL_SERVICE=smtps
      - STUNNEL_ACCEPT=465
      - STUNNEL_CONNECT=mailhog:1025
    ports:
      - 465:465

  loki:
    image: grafana/loki
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/loki-config.yaml -config.expand-env=true
    restart: always
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/loki-config.yaml
  
  promtail:
    image: grafana/promtail:latest
    ports:
      - 1514:1514/udp
      - 9080:9080/tcp
    command: -config.file=/etc/promtail/promtail-config.yaml -config.expand-env=true
    restart: always
    volumes:
    - ./promtail/promtail-config.yaml:/etc/promtail/promtail-config.yaml
    - /var/log:/var/log

  syslog-ng:
    command: -edv
    image: balabit/syslog-ng:latest
    ports:
      - 514:514/udp
      - 601:601/tcp
    restart: always
    volumes:
    - /etc/machine-id:/etc/machine-id:ro
    - /var/log/:/var/log/sys:ro
    - ./syslog-ng/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf 

